"""Rename session table column to session_key

Revision ID: 2b7faed33de1
Revises: 6de003b8fa4c
Create Date: 2024-10-22 18:02:33.017623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b7faed33de1"
down_revision: Union[str, None] = "6de003b8fa4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column("session_key", sa.String(length=255), nullable=False),
    )
    op.drop_constraint("unique_session_token", "sessions", type_="unique")
    op.create_unique_constraint(
        "unique_session_token", "sessions", ["session_key"]
    )
    op.create_unique_constraint(None, "sessions", ["session_key"])
    op.drop_column("sessions", "session_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "session_token",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "sessions", type_="unique")
    op.drop_constraint("unique_session_token", "sessions", type_="unique")
    op.create_unique_constraint(
        "unique_session_token", "sessions", ["session_token"]
    )
    op.drop_column("sessions", "session_key")
    # ### end Alembic commands ###
